# Generated by Django 3.0.7 on 2020-06-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_field',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
