# Generated by Django 3.0.7 on 2020-06-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200621_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='marked_correct',
            field=models.BooleanField(default=False),
        ),
    ]
